/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utilerias.BotonPersonalizado;
import utilerias.PanelTransparente;
import utilerias.PersonalizacionGeneral;

/**
 *
 * @author ruben
 */
public class PantallaResultado extends javax.swing.JFrame {

    
    String fondo = "recursos/interfaz/fondoConfiguracion.png";

        
    
    /**
     * Creates new form PantallaResultado
     */
   public PantallaResultado(String nombreGanador) {
    initComponents();
    cargarInterfaz();
    jblNombreGanador.setText(nombreGanador); // Actualiza el nombre del ganador en la etiqueta
}


    
    
    private void cargarInterfaz(){
        
        try {
            PersonalizacionGeneral.colocarImagenDesenfocadaLabel(jblFondo, fondo, 12);
            
            btnVolver.setContentAreaFilled(false);
            btnVolver.setBorderPainted(false);
            btnVolver.setOpaque(false);
            btnVolver.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));
            
            this.setShape(new RoundRectangle2D.Double(0, 0, 650, 400, 30, 30));
            
            ventanaArrastrable();

            
        }
        
        catch (IOException ex) {
            Logger.getLogger(PantallaResultado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    private void ventanaArrastrable(){
        Point mouseClick = new Point();
        
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                mouseClick.x = e.getX();
                mouseClick.y = e.getY();
            }
        });
        
        
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point location = PantallaResultado.this.getLocation();
                PantallaResultado.this.setLocation(
                    location.x + e.getX() - mouseClick.x,
                    location.y + e.getY() - mouseClick.y
                );
            }
        });
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanel1 = new PanelTransparente((float) 0.35);
        jblGanador = new javax.swing.JLabel();
        jblNombreGanador = new javax.swing.JLabel();
        jPanelHead = new javax.swing.JPanel();
        jblResultado = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultado");
        setMinimumSize(new java.awt.Dimension(650, 400));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 400));

        jPanelFondo.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblGanador.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jblGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblGanador.setText("Ganador");

        jblNombreGanador.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jblNombreGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreGanador.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jblNombreGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombreGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanel1);
        jPanel1.setBounds(100, 120, 470, 160);

        jPanelHead.setBackground(new java.awt.Color(13, 26, 51));

        jblResultado.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jblResultado.setForeground(new java.awt.Color(255, 255, 255));
        jblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblResultado.setText("Resultado");

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeadLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeadLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblResultado)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        jPanelFondo.add(jPanelHead);
        jPanelHead.setBounds(0, 0, 650, 50);

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnVolver);
        btnVolver.setBounds(50, 333, 120, 40);
        jPanelFondo.add(jblFondo);
        jblFondo.setBounds(0, 50, 650, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnVolverMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JLabel jblGanador;
    private javax.swing.JLabel jblNombreGanador;
    private javax.swing.JLabel jblResultado;
    // End of variables declaration//GEN-END:variables
}
