/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.awt.Color;
import java.io.IOException;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import utilerias.BotonPersonalizado;
import utilerias.PersonalizacionGeneral;
import BusEvent.*;
/**
 *
 * @author ruben
 */
public class PantallaEscogerPartida extends javax.swing.JFrame {

    String fondo = "recursos/interfaz/fondoEscogerPartida.png";

    private BusEvent.EventBus.Subscription subscripcion;
    PantallaPrincipal inicio;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaEscogerPartida(PantallaPrincipal inicio) {
        initComponents();

        this.inicio = inicio;
        cargarInterfaz();

    }

    
    
    private void cargarInterfaz() {
        try {

            PersonalizacionGeneral.colocarImagenLabel(jblFondo, fondo);
            personazilarBotones();

        } catch (Exception ex) {
            Logger.getLogger(PantallaEscogerPartida.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void personazilarBotones() {

        btnCrear.setContentAreaFilled(false);
        btnCrear.setBorderPainted(false);
        btnCrear.setOpaque(false);
        btnCrear.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));

        btnUnirse.setContentAreaFilled(false);
        btnUnirse.setBorderPainted(false);
        btnUnirse.setOpaque(false);
        btnUnirse.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));

        btnVolver.setContentAreaFilled(false);
        btnVolver.setBorderPainted(false);
        btnVolver.setOpaque(false);
        btnVolver.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jblConfiguracion = new javax.swing.JLabel();
        jPanelDerechos = new javax.swing.JPanel();
        jblDerechos = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalla Naval");
        setMinimumSize(new java.awt.Dimension(950, 600));
        setSize(new java.awt.Dimension(950, 600));

        jPanelFondo.setLayout(null);

        jPanelHead.setBackground(new java.awt.Color(13, 26, 51));

        jblConfiguracion.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jblConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        jblConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConfiguracion.setText("Escoger partida");

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelFondo.add(jPanelHead);
        jPanelHead.setBounds(0, 0, 0, 0);

        jPanelDerechos.setBackground(new java.awt.Color(13, 26, 51));

        jblDerechos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblDerechos.setForeground(new java.awt.Color(255, 255, 255));
        jblDerechos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDerechos.setText("© 2025 Batalla Naval. Todos los derechos reservados.");

        javax.swing.GroupLayout jPanelDerechosLayout = new javax.swing.GroupLayout(jPanelDerechos);
        jPanelDerechos.setLayout(jPanelDerechosLayout);
        jPanelDerechosLayout.setHorizontalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDerechosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblDerechos, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDerechosLayout.setVerticalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblDerechos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanelDerechos);
        jPanelDerechos.setBounds(0, 550, 950, 50);

        btnVolver.setBackground(new java.awt.Color(0, 166, 255));
        btnVolver.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnVolver);
        btnVolver.setBounds(50, 440, 200, 60);

        btnCrear.setBackground(new java.awt.Color(0, 166, 255));
        btnCrear.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnCrear.setText("Crear Sala");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnCrear);
        btnCrear.setBounds(50, 200, 200, 60);

        btnUnirse.setBackground(new java.awt.Color(0, 166, 255));
        btnUnirse.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnUnirse.setText("<html><center>Uniserse a <br> una Sala</center></html>");
        btnUnirse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnirseMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnUnirse);
        btnUnirse.setBounds(50, 320, 200, 60);
        jPanelFondo.add(jblFondo);
        jblFondo.setBounds(0, 0, 950, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        
            
        
//        new Thread(() -> {
//            try {
//                ServerSocket servidor = new ServerSocket(5000);
//                System.out.println("Esperando a un jugador...");
//                
//                InetAddress ip = InetAddress.getLocalHost();
//                System.out.println("Tu IP local es: " + ip.getHostAddress());
//                
//                
//                Socket socketCliente = servidor.accept();
//                System.out.println("Conexión establecida con el servidor");
//                
//
//                PantallaAsignacion asignacion = new PantallaAsignacion(this, socketCliente, true); // true = soy servidor
//                asignacion.setVisible(true);
//                this.setVisible(false);
//
//
//            } catch (IOException ex) {
//                ex.printStackTrace();
//                JOptionPane.showMessageDialog(this, "Error al crear la sala.", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        }).start();


        try{
        ServerSocket servidor = new ServerSocket(5000);

        PantallaAsignacion asignacion = new PantallaAsignacion(this, true); // sin socket aún
        asignacion.setVisible(true);
        this.setVisible(false);

        // Luego, en la clase PantallaAsignacion, abres un hilo para esperar la conexión
        asignacion.esperarConexionDelOponente(servidor);
        
        }
        
        catch(IOException e){
        
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnUnirseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnirseMouseClicked
        PantallaConexion conexion = new PantallaConexion(this);
        conexion.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnUnirseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanelDerechos;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JLabel jblConfiguracion;
    private javax.swing.JLabel jblDerechos;
    private javax.swing.JLabel jblFondo;
    // End of variables declaration//GEN-END:variables
}
