/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.awt.Color;
import utilerias.BotonPersonalizado;
import utilerias.PanelTransparente;
import utilerias.PersonalizacionGeneral;
import negocio.*;
import DAOs.JuegoDAO;
import javax.swing.*;

/**
 *
 * @author ruben
 */
public class PantallaAsignacion extends javax.swing.JFrame {

    private Tablero tableroJugador;
    private JButton[][] botonesTablero = new JButton[10][10];
    private String orientacionActual = "horizontal"; // horizontal por defecto
    private TipoBarco tipoSeleccionado = TipoBarco.BARCO; // Tipo por defecto (puedes mejorarlo luego)
    private ViewModels.AsignacionViewModel vmAsignacion;
    private boolean esJugador1 = true; // Empezamos con jugador 1
    private Tablero tableroJugador1;
    private Tablero tableroJugador2;

    String fondo = "recursos/interfaz/fondoPantallaPartida.png";

    PantallaEscogerPartida escoger;

    /**
     * Creates new form PantallaAsignacion
     *
     * @param escoger
     */
    public PantallaAsignacion(PantallaEscogerPartida escoger) {
        initComponents();

        this.escoger = escoger;

        cargarInterfaz();
    }

    private void cargarInterfaz() {

        PersonalizacionGeneral.colocarImagenLabel(jblFondo, fondo);
        // PersonalizacionGeneral.imagenAJLabelMaxCalidad(jblIconApuntar, "recursos/iconos/apuntar.png");

        personazilarBotones();
        vmAsignacion = new ViewModels.AsignacionViewModel();
        crearTablero();

    }

    private void colocarBarco(int x, int y) {
        Barco barco = new Barco(tipoSeleccionado, 3, orientacionActual); // Ejemplo: tamaño 3
        boolean colocado = tableroJugador.colocarBarco(barco, x, y);

        if (colocado) {
            // Pintar celdas
            if (orientacionActual.equals("horizontal")) {
                for (int i = 0; i < barco.getTamaño(); i++) {
                    botonesTablero[x + i][y].setBackground(Color.GRAY);
                }
            } else {
                for (int i = 0; i < barco.getTamaño(); i++) {
                    botonesTablero[x][y + i].setBackground(Color.GRAY);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo colocar el barco aquí", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void crearTablero() {
        JPanel panelGrid = new JPanel(new java.awt.GridLayout(10, 10));
        panelGrid.setBounds(20, 170, 355, 325);
        panelGrid.setOpaque(false);

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                JButton boton = new JButton();
                boton.setBackground(new Color(173, 216, 230));
                boton.setFocusPainted(false);
                int x = i;
                int y = j;

                boton.addActionListener(e -> colocarBarco(x, y));

                botonesTablero[i][j] = boton;
                panelGrid.add(boton);
            }
        }

        this.add(panelGrid, 0);
    }

    private void personazilarBotones() {

        btnConfirmar.setContentAreaFilled(false);
        btnConfirmar.setBorderPainted(false);
        btnConfirmar.setOpaque(false);
        btnConfirmar.setUI(new BotonPersonalizado(25, new Color(21, 255, 0), new Color(21, 255, 168), 3));

        btnVolver.setContentAreaFilled(false);
        btnVolver.setBorderPainted(false);
        btnVolver.setOpaque(false);
        btnVolver.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));

        btnGirar.setContentAreaFilled(false);
        btnGirar.setBorderPainted(false);
        btnGirar.setOpaque(false);
        btnGirar.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jblConfiguracion1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jPanelTiposNaves = new PanelTransparente((float) 0.35);
        jblTiposNave = new javax.swing.JLabel();
        jPanelNombreJugador = new PanelTransparente((float) 0.35);
        jblNombreJugador = new javax.swing.JLabel();
        jPanelEsperando = new PanelTransparente((float) 0.35);
        jblEsperando = new javax.swing.JLabel();
        jPanelDerechos = new javax.swing.JPanel();
        jblDerechos = new javax.swing.JLabel();
        jblIconApuntar = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnGirar = new javax.swing.JButton();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asignar Barcos");

        jPanelFondo.setLayout(null);

        jPanelHead.setBackground(new java.awt.Color(13, 26, 51));
        jPanelHead.setLayout(null);

        jblConfiguracion1.setFont(new java.awt.Font("Monospaced", 0, 22)); // NOI18N
        jblConfiguracion1.setForeground(new java.awt.Color(255, 255, 255));
        jblConfiguracion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConfiguracion1.setText("ID partida: 172.72.82...");
        jPanelHead.add(jblConfiguracion1);
        jblConfiguracion1.setBounds(235, 6, 412, 47);

        btnVolver.setBackground(new java.awt.Color(0, 166, 255));
        btnVolver.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanelHead.add(btnVolver);
        btnVolver.setBounds(21, 14, 120, 35);

        jPanelFondo.add(jPanelHead);
        jPanelHead.setBounds(0, 0, 950, 60);

        jPanelTiposNaves.setBackground(new java.awt.Color(255, 255, 255));

        jblTiposNave.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jblTiposNave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblTiposNave.setText("Tipos de nave");

        javax.swing.GroupLayout jPanelTiposNavesLayout = new javax.swing.GroupLayout(jPanelTiposNaves);
        jPanelTiposNaves.setLayout(jPanelTiposNavesLayout);
        jPanelTiposNavesLayout.setHorizontalGroup(
            jPanelTiposNavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposNavesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblTiposNave, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelTiposNavesLayout.setVerticalGroup(
            jPanelTiposNavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposNavesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblTiposNave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelTiposNaves);
        jPanelTiposNaves.setBounds(500, 130, 360, 32);

        jPanelNombreJugador.setBackground(new java.awt.Color(255, 255, 255));

        jblNombreJugador.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jblNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblNombreJugador.setText("Tablero de: Jack Sparrow");

        javax.swing.GroupLayout jPanelNombreJugadorLayout = new javax.swing.GroupLayout(jPanelNombreJugador);
        jPanelNombreJugador.setLayout(jPanelNombreJugadorLayout);
        jPanelNombreJugadorLayout.setHorizontalGroup(
            jPanelNombreJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNombreJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanelNombreJugadorLayout.setVerticalGroup(
            jPanelNombreJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNombreJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblNombreJugador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelNombreJugador);
        jPanelNombreJugador.setBounds(20, 130, 360, 32);

        jPanelEsperando.setBackground(new java.awt.Color(255, 255, 255));

        jblEsperando.setFont(new java.awt.Font("Monospaced", 1, 22)); // NOI18N
        jblEsperando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblEsperando.setText("Esperando Jugadores");

        javax.swing.GroupLayout jPanelEsperandoLayout = new javax.swing.GroupLayout(jPanelEsperando);
        jPanelEsperando.setLayout(jPanelEsperandoLayout);
        jPanelEsperandoLayout.setHorizontalGroup(
            jPanelEsperandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEsperandoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblEsperando, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanelEsperandoLayout.setVerticalGroup(
            jPanelEsperandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEsperandoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblEsperando, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelEsperando);
        jPanelEsperando.setBounds(510, 470, 360, 50);

        jPanelDerechos.setBackground(new java.awt.Color(13, 26, 51));

        jblDerechos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblDerechos.setForeground(new java.awt.Color(255, 255, 255));
        jblDerechos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDerechos.setText("© 2025 Batalla Naval. Todos los derechos reservados.");

        javax.swing.GroupLayout jPanelDerechosLayout = new javax.swing.GroupLayout(jPanelDerechos);
        jPanelDerechos.setLayout(jPanelDerechosLayout);
        jPanelDerechosLayout.setHorizontalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDerechosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblDerechos, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDerechosLayout.setVerticalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblDerechos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanelDerechos);
        jPanelDerechos.setBounds(0, 550, 950, 50);

        jblIconApuntar.setText("jLabel1");
        jPanelFondo.add(jblIconApuntar);
        jblIconApuntar.setBounds(515, 420, 32, 32);

        btnConfirmar.setBackground(new java.awt.Color(0, 166, 255));
        btnConfirmar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnConfirmar);
        btnConfirmar.setBounds(750, 415, 120, 40);

        btnGirar.setBackground(new java.awt.Color(0, 166, 255));
        btnGirar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnGirar.setText("Girar");
        btnGirar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGirarMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnGirar);
        btnGirar.setBounds(510, 415, 120, 40);

        jblFondo.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jPanelFondo.add(jblFondo);
        jblFondo.setBounds(0, 0, 950, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        if (esJugador1) {
            tableroJugador1 = vmAsignacion.getTablero(); // Guarda el tablero de jugador 1
            esJugador1 = false; // Cambia al jugador 2
            vmAsignacion = new ViewModels.AsignacionViewModel(); // Nuevo tablero para jugador 2
            limpiarTableroGUI();
            JOptionPane.showMessageDialog(this, "Turno del Jugador 2: Coloca tus barcos.");
        } else {
            tableroJugador2 = vmAsignacion.getTablero(); // Guarda el tablero de jugador 2
            abrirPantallaJuego(); // Iniciar la partida
        }
    }//GEN-LAST:event_btnConfirmarMouseClicked
    private void limpiarTableroGUI() {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                botonesTablero[i][j].setBackground(new Color(173, 216, 230)); // Azul claro
                botonesTablero[i][j].setEnabled(true);
            }
        }
    }

    private void abrirPantallaJuego() {
        PantallaJuego juego = new PantallaJuego(tableroJugador1, tableroJugador2);
        juego.setVisible(true);
        this.dispose();
    }


    private void btnGirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGirarMouseClicked
        if (orientacionActual.equals("horizontal")) {
            orientacionActual = "vertical";
        } else {
            orientacionActual = "horizontal";
        }
    }//GEN-LAST:event_btnGirarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        escoger.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnGirar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanelDerechos;
    private javax.swing.JPanel jPanelEsperando;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelNombreJugador;
    private javax.swing.JPanel jPanelTiposNaves;
    private javax.swing.JLabel jblConfiguracion1;
    private javax.swing.JLabel jblDerechos;
    private javax.swing.JLabel jblEsperando;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JLabel jblIconApuntar;
    private javax.swing.JLabel jblNombreJugador;
    private javax.swing.JLabel jblTiposNave;
    // End of variables declaration//GEN-END:variables
}
