/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import BusEvent.EventBus;
import BusEvent.EventoCambioUsuario;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilerias.BotonPersonalizado;
import utilerias.PersonalizacionGeneral;

/**
 *
 * @author ruben
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    
    String fondo = "recursos/interfaz/fondoPantallaInicial.png";
    
    
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        EventBus.suscribir(EventoCambioUsuario.class, evento -> {
    jblNombreUsuario.setText(evento.getNuevoNombre());
    jPanelColor.setBackground(evento.getNuevoColor());
});

        
        cargarInterfaz();
        
    }

    
    
    private void cargarInterfaz(){
        PersonalizacionGeneral.colocarImagenLabel(jblFondo, fondo);
        
        
        personazilarBotones();
    }
    
    
    private void personazilarBotones(){
        
        btnJugar.setContentAreaFilled(false);
        btnJugar.setBorderPainted(false);
        btnJugar.setOpaque(false);
        btnJugar.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255) ,3 ));
        
        
        btnOpciones.setContentAreaFilled(false);
        btnOpciones.setBorderPainted(false);
        btnOpciones.setOpaque(false);
        btnOpciones.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255) ,3));
        
        
        btnSalir.setContentAreaFilled(false);
        btnSalir.setBorderPainted(false);
        btnSalir.setOpaque(false);
        btnSalir.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255) ,3));
        
        cargarDatosUsuario();
        
    }
    
    private void cargarDatosUsuario(){
    
        String colorString = "";
            
            if(new File("jugador.txt").exists()){
            
                try (BufferedReader reader = new BufferedReader(new FileReader("jugador.txt"))) {
                    String linea;
                    while ((linea = reader.readLine()) != null) {
                        String[] partes = linea.split("=");
                        if (partes.length == 2) {
                            if (partes[0].equals("nombre")) {
                                //nombre = partes[1];
                                jblNombreUsuario.setText(partes[1]);
                            } else if (partes[0].equals("color")) {
                                colorString = partes[1];
                            }
                        }
                    }
                    
                    
                 if (colorString.equalsIgnoreCase("0,0,255")){
                jPanelColor.setBackground(new Color(0,0,255));
                }
            
                if (colorString.equalsIgnoreCase("51,255,51")){
                    jPanelColor.setBackground(new Color(51,255,51));
                }


                if (colorString.equalsIgnoreCase("204,0,204")){
                    jPanelColor.setBackground(new Color(204,0,204));
                }

                if (colorString.equalsIgnoreCase("0,255,255")){
                    jPanelColor.setBackground(new Color(0,255,255));
                }


            } 
                  
            catch (FileNotFoundException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            catch (IOException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
            
            }
        
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelDerechos = new javax.swing.JPanel();
        jPanelColor = new javax.swing.JPanel();
        jblNombreUsuario = new javax.swing.JLabel();
        jblDerechos = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalla Naval");
        setMinimumSize(new java.awt.Dimension(950, 600));
        setSize(new java.awt.Dimension(950, 600));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanelFondo.setLayout(null);

        jPanelDerechos.setBackground(new java.awt.Color(13, 26, 51));

        jPanelColor.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jblNombreUsuario.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jblNombreUsuario.setText("Usuario No Configurado");

        jblDerechos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblDerechos.setForeground(new java.awt.Color(255, 255, 255));
        jblDerechos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDerechos.setText("© 2025 Batalla Naval. Todos los derechos reservados.");

        javax.swing.GroupLayout jPanelDerechosLayout = new javax.swing.GroupLayout(jPanelDerechos);
        jPanelDerechos.setLayout(jPanelDerechosLayout);
        jPanelDerechosLayout.setHorizontalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDerechosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jblDerechos, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDerechosLayout.setVerticalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDerechosLayout.createSequentialGroup()
                .addComponent(jblDerechos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDerechosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelColor, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelFondo.add(jPanelDerechos);
        jPanelDerechos.setBounds(0, 550, 950, 50);

        btnSalir.setBackground(new java.awt.Color(0, 166, 255));
        btnSalir.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnSalir);
        btnSalir.setBounds(340, 400, 250, 80);

        btnJugar.setBackground(new java.awt.Color(0, 166, 255));
        btnJugar.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJugarMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnJugar);
        btnJugar.setBounds(340, 120, 250, 80);

        btnOpciones.setBackground(new java.awt.Color(0, 166, 255));
        btnOpciones.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnOpciones.setText("Opciones");
        btnOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpcionesMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnOpciones);
        btnOpciones.setBounds(340, 260, 250, 80);
        jPanelFondo.add(jblFondo);
        jblFondo.setBounds(0, 0, 950, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJugarMouseClicked
        // TODO add your handling code here:
        
        if(new File("jugador.txt").exists()){
                
            PantallaEscogerPartida partida = new PantallaEscogerPartida(this);
            partida.setVisible(true);
            this.setVisible(false);
        }  
        
        else{
            JOptionPane.showMessageDialog(this, "Debe configurar su nombre de usuario y color", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btnJugarMouseClicked

    private void btnOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcionesMouseClicked
        // TODO add your handling code here:
        
        PantallaConfiguracion confi = new PantallaConfiguracion(this);
        confi.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btnOpcionesMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        cargarDatosUsuario();
        
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JPanel jPanelDerechos;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JLabel jblDerechos;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JLabel jblNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
