/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.awt.Color;
import utilerias.BotonPersonalizado;
import utilerias.PanelTransparente;
import utilerias.PersonalizacionGeneral;
import negocio.*;
import DAOs.JuegoDAO;
import javax.swing.*;

/**
 *
 * @author ruben
 */
public class PantallaJuego extends javax.swing.JFrame {

    private ViewModels.JuegoViewModel vmJuego;
    private JButton[][] botonesTablero = new JButton[10][10];

    private Tablero tableroCPU;

    String fondo = "recursos/interfaz/fondoColocarBarcos.png";

    /**
     * Creates new form PantallaJuego
     */
   public PantallaJuego(Tablero tableroJugador1, Tablero tableroJugador2) {
    initComponents();
    this.vmJuego = new ViewModels.JuegoViewModel(tableroJugador1, tableroJugador2);
    cargarInterfaz();
}


    private void cargarInterfaz() {

        PersonalizacionGeneral.colocarImagenLabel(jblFondo, fondo);

        personazilarBotones();
        crearTablero();
    }

    private void personazilarBotones() {

        btnAbandonar.setContentAreaFilled(false);
        btnAbandonar.setBorderPainted(false);
        btnAbandonar.setOpaque(false);
        btnAbandonar.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));

        btnAtacar.setContentAreaFilled(false);
        btnAtacar.setBorderPainted(false);
        btnAtacar.setOpaque(false);
        btnAtacar.setUI(new BotonPersonalizado(25, new Color(0, 166, 255), new Color(82, 250, 255), 3));

    }

  private void crearTablero() {
    JPanel panelGrid = new JPanel(new java.awt.GridLayout(10, 10));
    panelGrid.setBounds(100, 100, 400, 400);
    panelGrid.setOpaque(false);

    for (int i = 0; i < 10; i++) {
        for (int j = 0; j < 10; j++) {
            JButton boton = new JButton();
            boton.setBackground(new Color(173, 216, 230));
            boton.setFocusPainted(false);
            int x = i;
            int y = j;

            boton.addActionListener(e -> disparar(x, y));

            botonesTablero[i][j] = boton;
            panelGrid.add(boton);
        }
    }

    this.getContentPane().add(panelGrid);
}


   private void disparar(int x, int y) {
    boolean impacto = vmJuego.disparar(x, y);

    if (impacto) {
        botonesTablero[x][y].setBackground(Color.RED);
    } else {
        botonesTablero[x][y].setBackground(Color.WHITE);
    }

    botonesTablero[x][y].setEnabled(false);

    if (vmJuego.verificarGanador()) {
        String ganador = vmJuego.esTurnoJugador1() ? "Jugador 1" : "Jugador 2";
        JOptionPane.showMessageDialog(this, ganador + " ha ganado la partida!");
    } else {
        vmJuego.cambiarTurno();
        actualizarTurnoEnPantalla();
    }
}
private void actualizarTurnoEnPantalla() {
    if (vmJuego.esTurnoJugador1()) {
        jblTurno.setText("Turno: Jugador 1");
    } else {
        jblTurno.setText("Turno: Jugador 2");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jblTurno = new javax.swing.JLabel();
        btnAbandonar = new javax.swing.JButton();
        jblTiempo = new javax.swing.JLabel();
        jPanelTiposNaves = new PanelTransparente((float) 0.35);
        jblTiposNave = new javax.swing.JLabel();
        jPanelNombreJugador = new PanelTransparente((float) 0.35);
        jblNombreJugador = new javax.swing.JLabel();
        jPanelDerechos = new javax.swing.JPanel();
        jblDerechos = new javax.swing.JLabel();
        btnAtacar = new javax.swing.JButton();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setLayout(null);

        jPanelHead.setBackground(new java.awt.Color(13, 26, 51));

        jblTurno.setFont(new java.awt.Font("Monospaced", 0, 22)); // NOI18N
        jblTurno.setForeground(new java.awt.Color(255, 255, 255));
        jblTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTurno.setText("Turno: Jack Sparrow");

        btnAbandonar.setBackground(new java.awt.Color(0, 166, 255));
        btnAbandonar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnAbandonar.setText("Abandonar");
        btnAbandonar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbandonarMouseClicked(evt);
            }
        });

        jblTiempo.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        jblTiempo.setForeground(new java.awt.Color(255, 255, 255));
        jblTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTiempo.setText("30");

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnAbandonar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(787, Short.MAX_VALUE))
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeadLayout.createSequentialGroup()
                    .addContainerGap(235, Short.MAX_VALUE)
                    .addComponent(jblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(303, Short.MAX_VALUE)))
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeadLayout.createSequentialGroup()
                    .addGap(857, 857, 857)
                    .addComponent(jblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeadLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnAbandonar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeadLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
            .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeadLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(jblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanelFondo.add(jPanelHead);
        jPanelHead.setBounds(0, 0, 0, 0);

        jPanelTiposNaves.setBackground(new java.awt.Color(255, 255, 255));

        jblTiposNave.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jblTiposNave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblTiposNave.setText("Tablero de: Jugador 2");

        javax.swing.GroupLayout jPanelTiposNavesLayout = new javax.swing.GroupLayout(jPanelTiposNaves);
        jPanelTiposNaves.setLayout(jPanelTiposNavesLayout);
        jPanelTiposNavesLayout.setHorizontalGroup(
            jPanelTiposNavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposNavesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblTiposNave, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelTiposNavesLayout.setVerticalGroup(
            jPanelTiposNavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposNavesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblTiposNave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelTiposNaves);
        jPanelTiposNaves.setBounds(500, 90, 360, 32);

        jPanelNombreJugador.setBackground(new java.awt.Color(255, 255, 255));

        jblNombreJugador.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jblNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblNombreJugador.setText("Tablero de: Jack Sparrow");

        javax.swing.GroupLayout jPanelNombreJugadorLayout = new javax.swing.GroupLayout(jPanelNombreJugador);
        jPanelNombreJugador.setLayout(jPanelNombreJugadorLayout);
        jPanelNombreJugadorLayout.setHorizontalGroup(
            jPanelNombreJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNombreJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanelNombreJugadorLayout.setVerticalGroup(
            jPanelNombreJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNombreJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblNombreJugador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelNombreJugador);
        jPanelNombreJugador.setBounds(20, 90, 360, 32);

        jPanelDerechos.setBackground(new java.awt.Color(13, 26, 51));

        jblDerechos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblDerechos.setForeground(new java.awt.Color(255, 255, 255));
        jblDerechos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDerechos.setText("© 2025 Batalla Naval. Todos los derechos reservados.");

        javax.swing.GroupLayout jPanelDerechosLayout = new javax.swing.GroupLayout(jPanelDerechos);
        jPanelDerechos.setLayout(jPanelDerechosLayout);
        jPanelDerechosLayout.setHorizontalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDerechosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblDerechos, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDerechosLayout.setVerticalGroup(
            jPanelDerechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblDerechos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanelDerechos);
        jPanelDerechos.setBounds(0, 550, 950, 50);

        btnAtacar.setBackground(new java.awt.Color(0, 166, 255));
        btnAtacar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnAtacar.setText("Atacar");
        btnAtacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtacarMouseClicked(evt);
            }
        });
        jPanelFondo.add(btnAtacar);
        btnAtacar.setBounds(520, 490, 120, 35);

        jblFondo.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jPanelFondo.add(jblFondo);
        jblFondo.setBounds(0, 0, 950, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbandonarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbandonarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbandonarMouseClicked

    private void btnAtacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtacarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtacarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnAtacar;
    private javax.swing.JPanel jPanelDerechos;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelNombreJugador;
    private javax.swing.JPanel jPanelTiposNaves;
    private javax.swing.JLabel jblDerechos;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JLabel jblNombreJugador;
    private javax.swing.JLabel jblTiempo;
    private javax.swing.JLabel jblTiposNave;
    private javax.swing.JLabel jblTurno;
    // End of variables declaration//GEN-END:variables
}
